spring.application.name=flickgram

spring.datasource.url = jdbc:mysql://localhost:3306/springdb
spring.datasource.username = root
spring.datasource.password = P@rag120503

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true